# -*- coding: utf-8 -*-
"""cvi formulas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15jl32wbrXNY8I2HaK4hSK3ZrpCw4Zk65
"""

#thin lens equation

#given the distance of the object from the lens (u) and the distance of the image from the lens (v)
def find_f(u,v):
  (1/f) = (1/u) + (1/v)
  print(f)
  return f

#given the distance of the object from the lens (u) and the focal length (f)
def find_v(f,u):
  (1/v) = (1/f) - (1/u)
  print(v)
  return v

#given the distance of the distance of the image from the lens (v) and the focal length (f)
def find_u(f,v):
  (1/u) = (1/f) - (1/v)
  print(u)
  return u



